checks:
    php: true
filter: {  }
coding_style:
    php: {  }
build:
    environment:
        php: '5.6.16'
        mongodb: true
    tests:
        override:
            -
                command: './vendor/phpunit/phpunit/phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'
filter:
    excluded_path: [vendor/*, app/*, tests/*]
