language: php

services: mongodb

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_install: phpenv config-add travis.ini

before_script:
  - composer install -v

script:
  - ./vendor/phpunit/phpunit/phpunit